spring:
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/shops/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/moderation/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/cart/**

        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - StripPrefix=1

        - id: product-service-swagger
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs
          filters:
            - StripPrefix=1

        - id: order-service-swagger
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Gateway service
        url: /v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Product Service
        url: /product-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs

  api-docs:
    enabled: true

  enable-native-support: true
  swagger-ui.enable-spring-security: false